-- ============================================================
-- HOSPITAL MANAGEMENT SYSTEM — ANALYTICAL QUERIES
-- Demonstrates: JOINs, Aggregations, Subqueries, Window Functions,
--               CTEs, GROUP BY/HAVING, Date functions, CASE statements
-- ============================================================
USE hospital_management;

-- ------------------------------------------------------------
-- Q1. List all doctors with their department name (JOIN)
-- ------------------------------------------------------------
SELECT d.doctor_id, d.first_name, d.last_name, d.specialization,
       dept.department_name, d.years_experience, d.consultation_fee
FROM doctors d
JOIN departments dept ON d.department_id = dept.department_id
ORDER BY dept.department_name, d.years_experience DESC;


-- ------------------------------------------------------------
-- Q2. Total appointments and revenue generated by each doctor
--     (JOIN + Aggregation)
-- ------------------------------------------------------------
SELECT doc.doctor_id,
       CONCAT(doc.first_name, ' ', doc.last_name) AS doctor_name,
       doc.specialization,
       COUNT(a.appointment_id) AS total_appointments,
       SUM(CASE WHEN a.status = 'Completed' THEN 1 ELSE 0 END) AS completed_appointments,
       COALESCE(SUM(b.total_amount), 0) AS total_revenue
FROM doctors doc
LEFT JOIN appointments a ON doc.doctor_id = a.doctor_id
LEFT JOIN billing b ON a.appointment_id = b.appointment_id
GROUP BY doc.doctor_id, doctor_name, doc.specialization
ORDER BY total_revenue DESC;


-- ------------------------------------------------------------
-- Q3. Patients who have visited more than 3 times
--     (GROUP BY + HAVING)
-- ------------------------------------------------------------
SELECT p.patient_id, CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
       p.city, COUNT(a.appointment_id) AS visit_count
FROM patients p
JOIN appointments a ON p.patient_id = a.patient_id
GROUP BY p.patient_id, patient_name, p.city
HAVING COUNT(a.appointment_id) > 3
ORDER BY visit_count DESC;


-- ------------------------------------------------------------
-- Q4. Monthly revenue trend (Date functions + Aggregation)
-- ------------------------------------------------------------
SELECT DATE_FORMAT(b.bill_date, '%Y-%m') AS billing_month,
       COUNT(b.bill_id) AS total_bills,
       SUM(b.total_amount) AS monthly_revenue,
       ROUND(AVG(b.total_amount), 2) AS avg_bill_amount
FROM billing b
GROUP BY billing_month
ORDER BY billing_month;


-- ------------------------------------------------------------
-- Q5. Department-wise performance summary
--     (Multi-table JOIN + Aggregation)
-- ------------------------------------------------------------
SELECT dept.department_name,
       COUNT(DISTINCT doc.doctor_id) AS num_doctors,
       COUNT(DISTINCT a.appointment_id) AS total_appointments,
       COUNT(DISTINCT a.patient_id) AS unique_patients,
       COALESCE(SUM(b.total_amount), 0) AS department_revenue
FROM departments dept
LEFT JOIN doctors doc ON dept.department_id = doc.department_id
LEFT JOIN appointments a ON doc.doctor_id = a.doctor_id
LEFT JOIN billing b ON a.appointment_id = b.appointment_id
GROUP BY dept.department_name
ORDER BY department_revenue DESC;


-- ------------------------------------------------------------
-- Q6. Find patients who have NEVER cancelled an appointment
--     (Subquery with NOT IN)
-- ------------------------------------------------------------
SELECT patient_id, CONCAT(first_name, ' ', last_name) AS patient_name
FROM patients
WHERE patient_id NOT IN (
    SELECT DISTINCT patient_id
    FROM appointments
    WHERE status = 'Cancelled'
);


-- ------------------------------------------------------------
-- Q7. Top 5 most common diagnoses
--     (JOIN + GROUP BY + LIMIT)
-- ------------------------------------------------------------
SELECT t.diagnosis, COUNT(*) AS case_count
FROM treatments t
GROUP BY t.diagnosis
ORDER BY case_count DESC
LIMIT 5;


-- ------------------------------------------------------------
-- Q8. Patients with pending or partially paid bills
--     (JOIN + Filtering, useful for hospital admin/finance team)
-- ------------------------------------------------------------
SELECT p.patient_id, CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
       p.phone, b.bill_id, b.total_amount, b.payment_status, b.bill_date
FROM billing b
JOIN appointments a ON b.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE b.payment_status IN ('Pending', 'Partially Paid')
ORDER BY b.bill_date DESC;


-- ------------------------------------------------------------
-- Q9. Rank doctors within each department by revenue generated
--     (WINDOW FUNCTION — RANK)
-- ------------------------------------------------------------
SELECT department_name, doctor_name, total_revenue,
       RANK() OVER (PARTITION BY department_name ORDER BY total_revenue DESC) AS revenue_rank
FROM (
    SELECT dept.department_name,
           CONCAT(doc.first_name, ' ', doc.last_name) AS doctor_name,
           COALESCE(SUM(b.total_amount), 0) AS total_revenue
    FROM doctors doc
    JOIN departments dept ON doc.department_id = dept.department_id
    LEFT JOIN appointments a ON doc.doctor_id = a.doctor_id
    LEFT JOIN billing b ON a.appointment_id = b.appointment_id
    GROUP BY dept.department_name, doctor_name
) AS doctor_revenue
ORDER BY department_name, revenue_rank;


-- ------------------------------------------------------------
-- Q10. Running total of daily revenue (WINDOW FUNCTION — SUM OVER)
-- ------------------------------------------------------------
SELECT bill_date,
       SUM(total_amount) AS daily_revenue,
       SUM(SUM(total_amount)) OVER (ORDER BY bill_date) AS running_total_revenue
FROM billing
GROUP BY bill_date
ORDER BY bill_date;


-- ------------------------------------------------------------
-- Q11. Patient age distribution by category (CASE statement)
-- ------------------------------------------------------------
SELECT
    CASE
        WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) < 18 THEN 'Child (0-17)'
        WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) BETWEEN 18 AND 35 THEN 'Young Adult (18-35)'
        WHEN TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) BETWEEN 36 AND 60 THEN 'Adult (36-60)'
        ELSE 'Senior (60+)'
    END AS age_group,
    COUNT(*) AS patient_count
FROM patients
GROUP BY age_group
ORDER BY patient_count DESC;


-- ------------------------------------------------------------
-- Q12. Doctors with no-show rate above hospital average
--      (CTE + Subquery comparison)
-- ------------------------------------------------------------
WITH doctor_noshow AS (
    SELECT doctor_id,
           COUNT(*) AS total_appts,
           SUM(CASE WHEN status = 'No-Show' THEN 1 ELSE 0 END) AS no_shows,
           ROUND(SUM(CASE WHEN status = 'No-Show' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS noshow_rate
    FROM appointments
    GROUP BY doctor_id
)
SELECT doc.first_name, doc.last_name, dn.total_appts, dn.no_shows, dn.noshow_rate
FROM doctor_noshow dn
JOIN doctors doc ON dn.doctor_id = doc.doctor_id
WHERE dn.noshow_rate > (SELECT AVG(noshow_rate) FROM doctor_noshow)
ORDER BY dn.noshow_rate DESC;


-- ------------------------------------------------------------
-- Q13. Patients requiring follow-up that hasn't happened yet
--      (JOIN + Date comparison — useful for hospital reminders)
-- ------------------------------------------------------------
SELECT p.patient_id, CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
       p.phone, t.diagnosis, t.follow_up_date
FROM treatments t
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE t.follow_up_required = TRUE
  AND t.follow_up_date >= CURDATE()
ORDER BY t.follow_up_date ASC;


-- ------------------------------------------------------------
-- Q14. Revenue contribution % by payment method
--      (Aggregation + Window function for percentage)
-- ------------------------------------------------------------
SELECT payment_method,
       COUNT(*) AS num_transactions,
       SUM(total_amount) AS total_revenue,
       ROUND(SUM(total_amount) * 100.0 / SUM(SUM(total_amount)) OVER (), 2) AS pct_of_total_revenue
FROM billing
WHERE payment_method IS NOT NULL
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- ------------------------------------------------------------
-- Q15. Busiest appointment time slots (Hour-level analysis)
-- ------------------------------------------------------------
SELECT HOUR(appointment_time) AS appointment_hour,
       COUNT(*) AS num_appointments
FROM appointments
GROUP BY appointment_hour
ORDER BY num_appointments DESC;
